# Generated by Django 4.1.5 on 2023-02-25 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoSBBDDAPP', '0002_rename_usuarioxddd_usuario_delete_lole'),
    ]

    operations = [
        migrations.CreateModel(
            name='tecnico',
            fields=[
                ('codigo_tecnico', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='reporte',
            fields=[
                ('folio', models.BigAutoField(primary_key=True, serialize=False)),
                ('estado_reporte', models.BooleanField(default=False)),
                ('codigo_cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='proyectoSBBDDAPP.usuario')),
                ('codigo_tecnico', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='proyectoSBBDDAPP.tecnico')),
            ],
        ),
    ]
