# Generated by Django 4.1.5 on 2023-03-03 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoSBBDDAPP', '0005_carousel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carousel',
        ),
    ]
