# Generated by Django 4.1.5 on 2023-03-03 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoSBBDDAPP', '0006_delete_carousel'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='motivo_reporte',
            field=models.IntegerField(default=1),
        ),
    ]
