# Generated by Django 4.1.5 on 2023-03-03 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoSBBDDAPP', '0007_reporte_motivo_reporte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='codigo_cliente',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='proyectoSBBDDAPP.usuario'),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='codigo_tecnico',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='proyectoSBBDDAPP.tecnico'),
        ),
    ]
