# Generated by Django 4.1.5 on 2023-03-03 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoSBBDDAPP', '0008_alter_reporte_codigo_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='codigo_cliente',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='proyectoSBBDDAPP.usuario'),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='codigo_tecnico',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='proyectoSBBDDAPP.tecnico'),
        ),
    ]
