# Generated by Django 4.1.5 on 2023-03-03 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoSBBDDAPP', '0009_alter_reporte_codigo_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registros',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
