# Generated by Django 4.1.5 on 2023-03-03 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoSBBDDAPP', '0010_alter_registros_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registros',
            name='folio',
            field=models.IntegerField(default=1),
        ),
    ]
